apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
