apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: devsecops
  source:
    repoURL: https://github.com/mohidev-tech/devsecops-platform.git
    targetRevision: main
    path: deploy/helm/postgres
    helm:
      releaseName: app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
